export default {
  title: "O titulo",
  html: `
<P>LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISCING ELIT. CONSEQUENTIA EXQUIRERE, QUOAD SIT ID, QUOD VOLUMUS, EFFECTUM. EFFICIENS DICI POTEST. </P>

<UL>
	<LI>SEPTEM AUTEM ILLI NON SUO, SED POPULORUM SUFFRAGIO OMNIUM NOMINATI SUNT.</LI>
	<LI>QUACUMQUE ENIM INGREDIMUR, IN ALIQUA HISTORIA VESTIGIUM PONIMUS.</LI>
	<LI>VULGO ENIM DICITUR: IUCUNDI ACTI LABORES, NEC MALE EURIPIDESCONCLUDAM, SI POTERO, LATINE;</LI>
	<LI>DUO REGES: CONSTRUCTIO INTERRETE.</LI>
</UL>


<OL>
	<LI>TUBULO PUTAS DICERE?</LI>
	<LI>AB HOC AUTEM QUAEDAM NON MELIUS QUAM VETERES, QUAEDAM OMNINO RELICTA.</LI>
	<LI>CUR FORTIOR SIT, SI ILLUD, QUOD TUTE CONCEDIS, ASPERUM ET VIX FERENDUM PUTABIT?</LI>
	<LI>ETSI EA QUIDEM, QUAE ADHUC DIXISTI, QUAMVIS AD AETATEM RECTE ISTO MODO DICERENTUR.</LI>
</OL>


<BLOCKQUOTE CITE='HTTP://LORIPSUM.NET'>
	QUAE DILIGENTISSIME CONTRA ARISTONEM DICUNTUR A CHRYIPPO.
</BLOCKQUOTE>
`,
  background: false,
};
